<?php
/**
 * Created by PhpStorm.
 * Script Name: Ffmpeg.php
 * Create: 2017/11/17 11:08
 * Description: php-ffmpeg
 * Author: Doogie<fdj@kuryun.cn>
 */

namespace app\index\controller;

use think\Controller;
use FFMpeg\FFMpeg;

class Ffmpegtest extends Controller
{
    protected $ffmpeg;
    protected $uploadVideoPath;
    protected $uploadImagePath;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->ffmpeg = FFMpeg::create();
        $this->uploadImagePath = './uploads/img/';
        $this->uploadVideoPath = './uploads/video/';
    }

    public function frame()
    {
        $video = $this->ffmpeg->open($this->uploadVideoPath . 'Wildlife.wmv');
        $video->frame(\FFMpeg\Coordinate\TimeCode::fromSeconds(1))
            ->save($this->uploadImagePath . 'frame.jpg');
        /*$video->save(new FFMpeg\Format\Video\X264(), 'export-x264.mp4')
            ->save(new FFMpeg\Format\Video\WMV(), 'export-wmv.wmv')
            ->save(new FFMpeg\Format\Video\WebM(), 'export-webm.webm');*/
    }

    public function format()
    {
        $file = mime_content_type($this->uploadVideoPath . 'Wildlife.wmv');
        //dump($file);exit;
        $video = $this->ffmpeg->open($this->uploadVideoPath . 'IMG_1397.MOV');
        $format = new \FFMpeg\Format\Video\X264();
        $format->setKiloBitrate(1000)           // 视频码率
            ->setAudioChannels(2)               // 音频声道
            ->setAudioKiloBitrate(256);
        //dump($video);exit;
        $input_file = $this->uploadVideoPath . 'IMG_1397.MOV';
        $output_file = $this->uploadVideoPath . 'test.mp4';
        $command = "ffmpeg -i {$input_file}  -y  -async 1 -s 640x360  {$output_file}";
        $res = @exec($command);
        /*$res = $video
            //->save(new \FFMpeg\Format\Video\WMV(), 'Wildlife.mp4')
            ->save($format, $this->uploadVideoPath . 'Wildlife.mp4')
            ;*/
        dump($res);
    }

}