<?php
/**
 * Created by PhpStorm.
 * Script Name: Obtest.php
 * Create: 2019/6/10 14:10
 * Description:
 * Author: Doogie<fdj@kuryun.cn>
 */
namespace app\index\controller;
use think\Controller;

class Obtest extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        //ob_start();                   //打开缓冲区
        echo "Hello\n";               //输出
        //ob_end_flush();
        header("location: /index/obtest/header"); //把浏览器重定向到header
        //exit;
    }

    public function header()
    {
        echo 111;
    }
}